//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLabApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleModelContainer1 : DbContext
    {
        public ScheduleModelContainer1()
            : base("name=ScheduleModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student> StudentSet { get; set; }
        public DbSet<Teacher> TeacherSet { get; set; }
        public DbSet<Course> CourseSet { get; set; }
        public DbSet<StudentsCourse> StudentsCourseSet { get; set; }
    }
}
