//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLabApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsCourse
    {
        public StudentsCourse()
        {
            this.Student = new HashSet<Student>();
            this.Course = new HashSet<Course>();
        }
    
        public int StudentsCourseId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public int Appraisal { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Course> Course { get; set; }
    }
}
